[package]
name = "kurec"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
domain = { version = "0.1.0", path = "../../libs/domain" }
futures = "0.3.31"
mirakc = { version = "0.0.1", path = "../../libs/infra/mirakc" }
nats = { version = "0.0.1", path = "../../libs/infra/nats" }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
async-trait = "0.1.88"
